#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <Pipes.h>
#include <SocketLib.h>
void checkIsdecoded1();
void checkIsdecoded2();
void checkNodeComputeEngine11();
void checkNodeComputeEngine12();
void checkNodeComputeEngine21();
void checkNodeComputeEngine22();
void daemon_3();
void daemon_4();
void ebbyNo_initializer_in_progx_xoptx_xo();
void global_storage_initializer_();
void initInputs();
void initMem();
void initializeExtrinsicInfo11();
void initializeExtrinsicInfo12();
void initializeExtrinsicInfo21();
void initializeExtrinsicInfo22();
void initializeMessage11();
void initializeMessage12();
void initializeMessage21();
void initializeMessage22();
void initializeTransInfo11_12();
void initializeTransInfo12_11();
void initializeTransInfo21_22();
void initializeTransInfo22_21();
void initialize_aPosteriori1();
void initialize_aPosteriori2();
void initialize_aPriori1();
void initialize_aPriori2();
void progx_xoptx_xo_storage_initializer_();
void rate_initializer_in_progx_xoptx_xo();
void readCodeBlock();
void sendOther();
void send_aPosteriori();
void send_init_apriori1();
void send_init_apriori2();
void send_inputs();
void send_message();
void send_tens_info11_12();
void send_tens_info12_11();
void send_tens_info21_22();
void send_tens_info22_21();
void send_transverseCorrection11();
void send_transverseCorrection12();
void send_transverseCorrection21();
void send_transverseCorrection22();
void top_daemon_1();
void top_daemon_2();
void transverseCorrection11();
void transverseCorrection12();
void transverseCorrection21();
void transverseCorrection22();
void updateMessage11();
void updateMessage12();
void updateMessage21();
void updateMessage22();
void update_aPosteriori11();
void update_aPosteriori12();
void update_aPosteriori21();
void update_aPosteriori22();
