#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <Pipes.h>
#include <SocketLib.h>
void checkIsdecoded();
void checkNodeComputeEngine();
void ebbyNo_initializer_in_progx_xoptx_xo();
void global_storage_initializer_();
void initInputs();
void initializeExtrinsicInfo();
void initializeMessage();
void initialize_aPosteriori();
void initialize_aPriori();
void minSumDecode();
void progx_xoptx_xo_storage_initializer_();
void rate_initializer_in_progx_xoptx_xo();
void readCodeBlock();
void send_output();
void updateMessage();
void update_aPosteriori();
