#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <Pipes.h>
#include <SocketLib.h>
float absf(float f);
void checkIsdecoded();
void checkNodeComputeEngine();
void daemon();
void ebbyNo_initializer_in_progx_xoptx_xo();
void global_storage_initializer_();
void initInputs();
void initMem();
void initializeExtrinsicInfo();
void initializeMessage();
void initialize_aPosteriori();
void initialize_aPriori();
void progx_xoptx_xo_storage_initializer_();
void readCodeBlock();
void updateMessage();
