#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <Pipes.h>
#include <SocketLib.h>
void ebbyNo_initializer_in_progx_xoptx_xo();
void global_storage_initializer_();
void initInputs();
void initialize_aPriori();
void progx_xoptx_xo_storage_initializer_();
void rate_initializer_in_progx_xoptx_xo();
void readCodeBlock();
uint32_t send_output();
void top_daemon();
